### ISSUE TITLE
hidtest build fails on macOS: No rule to make target `hidtest.cpp'

### ISSUE THREAD

**Issue by LudovicRousseau** [libusb/hidapi#114] opened 2019-11-01 14:36 UTC
On macOS (Mojave 10.4.6) I have the error:
```
± make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in mac
make[2]: Nothing to be done for `all'.
Making all in hidtest
make[2]: *** No rule to make target `hidtest.cpp', needed by `hidtest.o'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

This is a regression caused by d98c408ed3939647cd2eef255fbb24b463b24622

If I rename the source code to `hidtestx.c` and adapt the `Makefile.am` I fix the issue.

I don't know why it fails. Maybe make is confused because the directory, the source code and the target have the same name?

```
± make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by Youw** [comment] 2019-11-02 20:37
Duplicate of #108

actually it affects all platforms  - no one cared to update manual Makefiles

@z3ntu suggests a fix for it: https://github.com/libusb/hidapi/issues/108#issuecomment-544919585

you may still use autotools to generate a working Makefile for it

**Closed** 2019-11-05 13:00 UTC
Labels: bug, macOS
